#!/bin/bash

# Ensure script is run with superuser privileges for system package management
if [[ $EUID -ne 0 ]]; then
   echo "This script must be run with superuser privileges." 
   exit 1
fi

# System package updates and installation
apt update
apt upgrade -y
apt install -y build-essential clangd git curl python3 net-tools

# Switch back to the regular user's home directory
USER_HOME=$(eval echo ~$SUDO_USER)

# Create directories if they don't exist
mkdir -p $USER_HOME/.config/nvim
mkdir -p $USER_HOME/.local/bin

# Clone repository
if [ ! -d "$USER_HOME/.config/nvim/kickstart.nvim" ]; then
    git clone https://github.com/nvim-lua/kickstart.nvim.git $USER_HOME/.config/nvim/kickstart.nvim
fi

# Download nvim.appimage
if [ ! -f "$USER_HOME/.local/bin/nvim.appimage" ]; then
    curl -LO https://github.com/neovim/neovim/releases/latest/download/nvim.appimage -o $USER_HOME/.local/bin/nvim.appimage
    chmod u+x $USER_HOME/.local/bin/nvim.appimage
fi

# Add aliases
echo -e "alias l='ls -la'\n\
alias srcbash='source ~/.bashrc'\n\
alias nvim='$USER_HOME/.local/bin/nvim.appimage'\n\
alias nv='nvim'\n\
alias cfbash-a='nv .bash_aliases'\n\
alias clr='clear'" >> $USER_HOME/.bash_aliases

# Source profile and bashrc (this may not have an effect when run within the script, but it's kept for completeness)
source $USER_HOME/.profile
source $USER_HOME/.bashrc

# Move files from kickstart.nvim to parent directory
mv $USER_HOME/.config/nvim/kickstart.nvim/* $USER_HOME/.config/nvim/

# Move hidden files/directories, excluding '..'
find $USER_HOME/.config/nvim/kickstart.nvim -maxdepth 1 ! -name . -a ! -name .. -exec mv {} $USER_HOME/.config/nvim/ \;

$USER_HOME/.local/bin/nvim.appimage
