#!/bin/bash

# Ensure script is run with superuser privileges for system package management
if [[ $EUID -ne 0 ]]; then
   echo "This script must be run with superuser privileges." 
   exit 1
fi

# System package updates and installation
apt update
apt upgrade -y
apt install -y build-essential clangd git curl python3 net-tools fuse

# Switch back to the regular user's home directory
USER_HOME=$(eval echo ~$SUDO_USER)

# Create directories if they don't exist
mkdir -p $USER_HOME/.config/nvim
mkdir -p $USER_HOME/.local/bin

# Clone repository
if [ ! -d "$USER_HOME/.config/nvim/kickstart.nvim" ]; then
    git clone https://github.com/nvim-lua/kickstart.nvim.git $USER_HOME/.config/nvim/kickstart.nvim
fi

# Download nvim.appimage
if [ ! -f "$USER_HOME/.local/bin/nvim.appimage" ]; then
    curl -Lo "$USER_HOME/.local/bin/nvim.appimage" https://github.com/neovim/neovim/releases/latest/download/nvim.appimage
    chmod u+x "$USER_HOME/.local/bin/nvim.appimage"
fi

# Add aliases
echo -e "#╭╮╱╱╱╱╱╱╱╭╮╱╱╱╱╭╮\n\
#┃┃╱╱╱╱╱╱╱┃┃╱╱╱╱┃┃\n\
#┃╰━┳━━┳━━┫╰━┳━━┫┃╭┳━━┳━━┳━━┳━━╮\n\
#┃╭╮┃╭╮┃━━┫╭╮┃╭╮┃┃┣┫╭╮┃━━┫┃━┫━━┫\n\
#┃╰╯┃╭╮┣━━┃┃┃┃╭╮┃╰┫┃╭╮┣━━┃┃━╋━━┃\n\
#╰━━┻╯╰┻━━┻╯╰┻╯╰┻━┻┻╯╰┻━━┻━━┻━━╯\n\
#==============================================================================\n\
# My own add ons for .bashrc\n\
#==============================================================================\n\
\n\
# shell shortcuts -------------------------------------------------------------\n\
\n\
# ls aliases\n\
alias l='ls -alhFv --group-directories'\n\
alias ll='ls -alF'\n\
alias la='ls -A'\n\
\n\
alias tree='tree -v --filesfirst'\n\
\n\
# shell shortcuts\n\
alias clr='clear && neofetch'\n\
alias srcbash='source ~/.bashrc && clr'\n\
alias srcprofile='source ~/.profile'\n\
alias mount='mount | column -t'\n\
alias locate='plocate'\n\
\n\
#backups\n\
alias bashrc-backup='cp ~/.bashrc ~/.backup_configs/.bashrc.backup'\n\
alias bash-a-backup='cp ~/.bash_aliases ~/.backup_configs/.bash_aliases.backup'\n\
alias profile-backup='cp ~/.profile ~/.backup_configs/.profile.backup'\n\
\n\
# abbreviations / most common paths -------------------------------------------\n\
\n\
# config shortcuts\n\
alias cfbash='nvim ~/.bashrc'\n\
alias cfbash-a='nvim ~/.bash_aliases'\n\
alias cfnvim='pushd ~/.config/nvim/'\n\
alias cfbash-s='pushd ~/.local/bin'\n\
alias cfsnippets='pushd /mnt/c/Users/arnca/AppData/Roaming/Code/User/snippets'\n\
\n\
# neovim\n\
alias nvim='nvim.appimage'\n\
alias nv='nvim -O'\n\
\n\
# cmake \n\
alias cmakebld='cmake --build .'\n\
\n\
# git aliases\n\
alias stats='git status -s'\n\
alias add-all='git add *'\n\
alias diff='git diff'\n\
alias log='git log'\n\
\n\
alias tarInfo='echo \"tar -xvpf filename.tar\"'\n\
\n\
# porgrams --------------------------------------------------------------------\n\
alias obs='flatpak run md.obsidian.Obsidian'\n\
\n\
# HTML VIEWING USING FIREFOX --------------------------------------------------\n\
alias firefox='/mnt/c/'Program Files'/'Mozilla Firefox'/./firefox.exe'\n\
\n\
# WINDOWS SPECIFIC ------------------------------------------------------------\n\
alias windowsInfo='echo 'Ctrl + R Type: msinfo32''\n\
 \n\
# mods ------------------------------------------------------------------------\n\
\n\
# removes the need for cd command. just need to type in path.\n\
shopt -s autocd\n\
#------------------------------------------------------------------------------" >> ~/.bash_aliases


# Source profile and bashrc (this may not have an effect when run within the script, but it's kept for completeness)
source $USER_HOME/.profile
source $USER_HOME/.bashrc

# Move files from kickstart.nvim to parent directory
mv $USER_HOME/.config/nvim/kickstart.nvim/* $USER_HOME/.config/nvim/

# Move hidden files/directories, excluding '..'
find $USER_HOME/.config/nvim/kickstart.nvim -maxdepth 1 ! -name . -a ! -name .. -exec mv {} $USER_HOME/.config/nvim/ \;

sudo chown -R $USER:$USER $HOME
~/.local/bin/nvim.appimage
